const body = [
  {
    album_group: "single",
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/6sZRrHvLZ3KKqtC2gq2eFM",
        },
        href: "https://api.spotify.com/v1/artists/6sZRrHvLZ3KKqtC2gq2eFM",
        id: "6sZRrHvLZ3KKqtC2gq2eFM",
        name: "Pxndxmxc X",
        type: "artist",
        uri: "spotify:artist:6sZRrHvLZ3KKqtC2gq2eFM",
      },
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/405szUsOpFpO87mUjNwMpA",
        },
        href: "https://api.spotify.com/v1/artists/405szUsOpFpO87mUjNwMpA",
        id: "405szUsOpFpO87mUjNwMpA",
        name: "TRINI-T OVERTUNE",
        type: "artist",
        uri: "spotify:artist:405szUsOpFpO87mUjNwMpA",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AG",
      "AL",
      "AM",
      "AO",
      "AR",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BW",
      "BY",
      "BZ",
      "CA",
      "CD",
      "CG",
      "CH",
      "CI",
      "CL",
      "CM",
      "CO",
      "CR",
      "CV",
      "CW",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "ET",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GR",
      "GT",
      "GW",
      "GY",
      "HK",
      "HN",
      "HR",
      "HT",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IQ",
      "IS",
      "IT",
      "JM",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "ML",
      "MN",
      "MO",
      "MR",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NI",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RO",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SL",
      "SM",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TN",
      "TO",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "US",
      "UY",
      "UZ",
      "VC",
      "VE",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/3r8XZemqbupZTfmOUL44eP",
    },
    href: "https://api.spotify.com/v1/albums/3r8XZemqbupZTfmOUL44eP",
    id: "3r8XZemqbupZTfmOUL44eP",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b2736cdfddd62c35ace2b05d9b39",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e026cdfddd62c35ace2b05d9b39",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d000048516cdfddd62c35ace2b05d9b39",
        width: 64,
      },
    ],
    name: "Society Distortion",
    release_date: "2020-07-13",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:3r8XZemqbupZTfmOUL44eP",
  },
]