const body = {
  body: {
    href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1/albums?include_groups=album,single,compilation,appears_on&offset=0&limit=20",
    items: [
      {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3QxX3NbWyLlLG6lP1xveL3",
        },
        href: "https://api.spotify.com/v1/albums/3QxX3NbWyLlLG6lP1xveL3",
        id: "3QxX3NbWyLlLG6lP1xveL3",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273f5e7b2e5adaa87430a3eccff",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02f5e7b2e5adaa87430a3eccff",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851f5e7b2e5adaa87430a3eccff",
            width: 64,
          },
        ],
        name: "Hypnotize",
        release_date: "2005-11-22",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:3QxX3NbWyLlLG6lP1xveL3",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0cn6MHyx4YuZauaB7Pb66o",
        },
        href: "https://api.spotify.com/v1/albums/0cn6MHyx4YuZauaB7Pb66o",
        id: "0cn6MHyx4YuZauaB7Pb66o",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273c65f8d04502eeddbdd61fa71",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02c65f8d04502eeddbdd61fa71",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851c65f8d04502eeddbdd61fa71",
            width: 64,
          },
        ],
        name: "Mezmerize",
        release_date: "2005-05-17",
        release_date_precision: "day",
        total_tracks: 11,
        type: "album",
        uri: "spotify:album:0cn6MHyx4YuZauaB7Pb66o",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6lA1sGw7eCv27bcpd5E0wT",
        },
        href: "https://api.spotify.com/v1/albums/6lA1sGw7eCv27bcpd5E0wT",
        id: "6lA1sGw7eCv27bcpd5E0wT",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2737cf4c0d42c5b62c9deebdcd8",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e027cf4c0d42c5b62c9deebdcd8",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048517cf4c0d42c5b62c9deebdcd8",
            width: 64,
          },
        ],
        name: "Steal This Album!",
        release_date: "2002-11-26",
        release_date_precision: "day",
        total_tracks: 16,
        type: "album",
        uri: "spotify:album:6lA1sGw7eCv27bcpd5E0wT",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6jWde94ln40epKIQCd8XUh",
        },
        href: "https://api.spotify.com/v1/albums/6jWde94ln40epKIQCd8XUh",
        id: "6jWde94ln40epKIQCd8XUh",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27330d45198d0c9e8841f9a9578",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0230d45198d0c9e8841f9a9578",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485130d45198d0c9e8841f9a9578",
            width: 64,
          },
        ],
        name: "Toxicity",
        release_date: "2001-09-04",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:6jWde94ln40epKIQCd8XUh",
      },
      {
        album_group: "album",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3sSfjX4fhZonjyZ10x0l0f",
        },
        href: "https://api.spotify.com/v1/albums/3sSfjX4fhZonjyZ10x0l0f",
        id: "3sSfjX4fhZonjyZ10x0l0f",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2732dc63e977bd5101072adcef6",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e022dc63e977bd5101072adcef6",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048512dc63e977bd5101072adcef6",
            width: 64,
          },
        ],
        name: "System Of A Down",
        release_date: "1998",
        release_date_precision: "year",
        total_tracks: 17,
        type: "album",
        uri: "spotify:album:3sSfjX4fhZonjyZ10x0l0f",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/00OQIrRjQgZmacSnjK8L7M",
        },
        href: "https://api.spotify.com/v1/albums/00OQIrRjQgZmacSnjK8L7M",
        id: "00OQIrRjQgZmacSnjK8L7M",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273ba00e990d1520a4cde41ce0c",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02ba00e990d1520a4cde41ce0c",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851ba00e990d1520a4cde41ce0c",
            width: 64,
          },
        ],
        name: "Protect The Land / Genocidal Humanoidz",
        release_date: "2020-11-06",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:00OQIrRjQgZmacSnjK8L7M",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6T2FD996HGKJ00rpuHHbu7",
        },
        href: "https://api.spotify.com/v1/albums/6T2FD996HGKJ00rpuHHbu7",
        id: "6T2FD996HGKJ00rpuHHbu7",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273c54b9260b13a275c546fb534",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02c54b9260b13a275c546fb534",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851c54b9260b13a275c546fb534",
            width: 64,
          },
        ],
        name: "Vicinity Of Obscenity/Lonely Day",
        release_date: "2006-05-29",
        release_date_precision: "day",
        total_tracks: 5,
        type: "album",
        uri: "spotify:album:6T2FD996HGKJ00rpuHHbu7",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AG",
          "AR",
          "AT",
          "BB",
          "BD",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BZ",
          "CA",
          "CL",
          "CO",
          "CR",
          "CW",
          "DE",
          "DM",
          "DO",
          "EC",
          "FM",
          "GD",
          "GT",
          "GY",
          "HK",
          "HN",
          "HT",
          "ID",
          "IN",
          "JM",
          "KH",
          "KN",
          "KR",
          "LA",
          "LC",
          "LK",
          "MO",
          "MV",
          "MX",
          "MY",
          "NI",
          "NP",
          "PA",
          "PE",
          "PH",
          "PK",
          "PY",
          "SG",
          "SR",
          "SV",
          "TH",
          "TL",
          "TT",
          "TW",
          "US",
          "UY",
          "VC",
          "VE",
          "VN",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0g7rLswEejduKye2DF7EfI",
        },
        href: "https://api.spotify.com/v1/albums/0g7rLswEejduKye2DF7EfI",
        id: "0g7rLswEejduKye2DF7EfI",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273353f5624c79de33285f3d006",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02353f5624c79de33285f3d006",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851353f5624c79de33285f3d006",
            width: 64,
          },
        ],
        name: "Hypnotize",
        release_date: "2005-10-11",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0g7rLswEejduKye2DF7EfI",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "BO",
          "BR",
          "CA",
          "CL",
          "FJ",
          "HK",
          "ID",
          "IN",
          "KI",
          "KR",
          "MH",
          "MX",
          "NR",
          "NZ",
          "PG",
          "PH",
          "PW",
          "PY",
          "SB",
          "SG",
          "TO",
          "TV",
          "US",
          "UY",
          "VU",
          "WS",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/34ZNizx7MgcKWtlj8FTbJO",
        },
        href: "https://api.spotify.com/v1/albums/34ZNizx7MgcKWtlj8FTbJO",
        id: "34ZNizx7MgcKWtlj8FTbJO",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27398429f352e43516e63950a60",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0298429f352e43516e63950a60",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485198429f352e43516e63950a60",
            width: 64,
          },
        ],
        name: "B.Y.O.B. single (with bonus)",
        release_date: "2005-05-03",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:34ZNizx7MgcKWtlj8FTbJO",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AG",
          "AR",
          "AU",
          "BB",
          "BO",
          "BR",
          "BS",
          "BZ",
          "CL",
          "CO",
          "CR",
          "CW",
          "DM",
          "DO",
          "EC",
          "FJ",
          "GD",
          "GT",
          "GY",
          "HN",
          "HT",
          "JM",
          "KI",
          "KN",
          "LC",
          "MH",
          "MX",
          "NI",
          "NR",
          "NZ",
          "PA",
          "PE",
          "PG",
          "PW",
          "PY",
          "SB",
          "SR",
          "SV",
          "TO",
          "TT",
          "TV",
          "US",
          "UY",
          "VC",
          "VE",
          "VU",
          "WS",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4dE7p4ZMRkx3yOjDWILwl8",
        },
        href: "https://api.spotify.com/v1/albums/4dE7p4ZMRkx3yOjDWILwl8",
        id: "4dE7p4ZMRkx3yOjDWILwl8",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27396ad8ea3886c8f3dbcc7fed9",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0296ad8ea3886c8f3dbcc7fed9",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485196ad8ea3886c8f3dbcc7fed9",
            width: 64,
          },
        ],
        name: "B.Y.O.B.",
        release_date: "2005-03-29",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:4dE7p4ZMRkx3yOjDWILwl8",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EG",
          "ES",
          "ET",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LU",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/41CBKm6FPUh28WPFj6UtNT",
        },
        href: "https://api.spotify.com/v1/albums/41CBKm6FPUh28WPFj6UtNT",
        id: "41CBKm6FPUh28WPFj6UtNT",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2736ef784594c984b3cc84ace75",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e026ef784594c984b3cc84ace75",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048516ef784594c984b3cc84ace75",
            width: 64,
          },
        ],
        name: "Lonely Day",
        release_date: "2005-01-01",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:41CBKm6FPUh28WPFj6UtNT",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "OM",
          "PA",
          "PE",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TR",
          "TT",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4PRYj7Apw5PmfcIeY4Zkf7",
        },
        href: "https://api.spotify.com/v1/albums/4PRYj7Apw5PmfcIeY4Zkf7",
        id: "4PRYj7Apw5PmfcIeY4Zkf7",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273ac57464cedcc7488d9281fce",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02ac57464cedcc7488d9281fce",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851ac57464cedcc7488d9281fce",
            width: 64,
          },
        ],
        name: "Chop Suey!",
        release_date: "2001-10-04",
        release_date_precision: "day",
        total_tracks: 4,
        type: "album",
        uri: "spotify:album:4PRYj7Apw5PmfcIeY4Zkf7",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AE",
          "AG",
          "AR",
          "BB",
          "BH",
          "BO",
          "BR",
          "BS",
          "BZ",
          "CL",
          "CO",
          "CR",
          "CW",
          "DM",
          "DO",
          "EC",
          "EG",
          "GB",
          "GD",
          "GT",
          "GY",
          "HN",
          "HT",
          "IE",
          "IQ",
          "JM",
          "JO",
          "JP",
          "KN",
          "KW",
          "LB",
          "LC",
          "LY",
          "MX",
          "NI",
          "OM",
          "PA",
          "PE",
          "PS",
          "PY",
          "QA",
          "SA",
          "SR",
          "SV",
          "TT",
          "UY",
          "VC",
          "VE",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6eHooNFxb0HVRmdWX3rCoZ",
        },
        href: "https://api.spotify.com/v1/albums/6eHooNFxb0HVRmdWX3rCoZ",
        id: "6eHooNFxb0HVRmdWX3rCoZ",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27356ca82b0ad2e288fd6db7b8b",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0256ca82b0ad2e288fd6db7b8b",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485156ca82b0ad2e288fd6db7b8b",
            width: 64,
          },
        ],
        name: "Toxicity",
        release_date: "1999",
        release_date_precision: "year",
        total_tracks: 3,
        type: "album",
        uri: "spotify:album:6eHooNFxb0HVRmdWX3rCoZ",
      },
      {
        album_group: "single",
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5eAWCfyUhZtHHtBdNk56l1",
            },
            href: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1",
            id: "5eAWCfyUhZtHHtBdNk56l1",
            name: "System Of A Down",
            type: "artist",
            uri: "spotify:artist:5eAWCfyUhZtHHtBdNk56l1",
          },
        ],
        available_markets: [
          "AE",
          "AG",
          "AR",
          "BB",
          "BH",
          "BO",
          "BR",
          "BS",
          "BZ",
          "CL",
          "CO",
          "CR",
          "DM",
          "DO",
          "EC",
          "EG",
          "GB",
          "GD",
          "GT",
          "GY",
          "HN",
          "HT",
          "IE",
          "IQ",
          "JM",
          "JO",
          "KN",
          "KW",
          "LC",
          "LY",
          "MX",
          "NI",
          "OM",
          "PA",
          "PE",
          "PS",
          "PY",
          "QA",
          "SA",
          "SR",
          "SV",
          "TT",
          "UY",
          "VC",
          "VE",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6rDpgWoxpfltcSxXK9JQqN",
        },
        href: "https://api.spotify.com/v1/albums/6rDpgWoxpfltcSxXK9JQqN",
        id: "6rDpgWoxpfltcSxXK9JQqN",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2732d98d071328230fa1d40b3ed",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e022d98d071328230fa1d40b3ed",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048512d98d071328230fa1d40b3ed",
            width: 64,
          },
        ],
        name: "Chop Suey!",
        release_date: "1999",
        release_date_precision: "year",
        total_tracks: 3,
        type: "album",
        uri: "spotify:album:6rDpgWoxpfltcSxXK9JQqN",
      },
      {
        album_group: "appears_on",
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/17Wa4geyiKRUsyTmB73elz",
        },
        href: "https://api.spotify.com/v1/albums/17Wa4geyiKRUsyTmB73elz",
        id: "17Wa4geyiKRUsyTmB73elz",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273d60088b045da48f6ed806630",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02d60088b045da48f6ed806630",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851d60088b045da48f6ed806630",
            width: 64,
          },
        ],
        name: "Rock Clássico",
        release_date: "2019-03-29",
        release_date_precision: "day",
        total_tracks: 79,
        type: "album",
        uri: "spotify:album:17Wa4geyiKRUsyTmB73elz",
      },
      {
        album_group: "appears_on",
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5PIDHpTCc6iT5WM2JZzFKu",
        },
        href: "https://api.spotify.com/v1/albums/5PIDHpTCc6iT5WM2JZzFKu",
        id: "5PIDHpTCc6iT5WM2JZzFKu",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273086d14bc1c05200680d290c9",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02086d14bc1c05200680d290c9",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851086d14bc1c05200680d290c9",
            width: 64,
          },
        ],
        name: "Loud Rocks",
        release_date: "2000-09-05",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:5PIDHpTCc6iT5WM2JZzFKu",
      },
      {
        album_group: "appears_on",
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3e89oGaupFgYKUIuE92Eb4",
        },
        href: "https://api.spotify.com/v1/albums/3e89oGaupFgYKUIuE92Eb4",
        id: "3e89oGaupFgYKUIuE92Eb4",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273437ee1c5b865adb9850570a0",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02437ee1c5b865adb9850570a0",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851437ee1c5b865adb9850570a0",
            width: 64,
          },
        ],
        name: "Music From The Motion Picture Not Another Teen Movie",
        release_date: "2001-04-01",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:3e89oGaupFgYKUIuE92Eb4",
      },
      {
        album_group: "appears_on",
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5kIE5Bm5P9h6KDsz46V2qc",
            },
            href: "https://api.spotify.com/v1/artists/5kIE5Bm5P9h6KDsz46V2qc",
            id: "5kIE5Bm5P9h6KDsz46V2qc",
            name: "Ara Malikian",
            type: "artist",
            uri: "spotify:artist:5kIE5Bm5P9h6KDsz46V2qc",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/4ILmz2oePyqUkGKvTkGd9q",
        },
        href: "https://api.spotify.com/v1/albums/4ILmz2oePyqUkGKvTkGd9q",
        id: "4ILmz2oePyqUkGKvTkGd9q",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27311c6091d6fbd008275fc9abd",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0211c6091d6fbd008275fc9abd",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485111c6091d6fbd008275fc9abd",
            width: 64,
          },
        ],
        name: "Royal Garage",
        release_date: "2019-05-17",
        release_date_precision: "day",
        total_tracks: 17,
        type: "album",
        uri: "spotify:album:4ILmz2oePyqUkGKvTkGd9q",
      },
      {
        album_group: "appears_on",
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1t987QQUIfdOwcCTI25j6J",
        },
        href: "https://api.spotify.com/v1/albums/1t987QQUIfdOwcCTI25j6J",
        id: "1t987QQUIfdOwcCTI25j6J",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273a72a36968ef25332ad07f932",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02a72a36968ef25332ad07f932",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851a72a36968ef25332ad07f932",
            width: 64,
          },
        ],
        name: "Pure... Hard Rock",
        release_date: "2011-06-06",
        release_date_precision: "day",
        total_tracks: 68,
        type: "album",
        uri: "spotify:album:1t987QQUIfdOwcCTI25j6J",
      },
      {
        album_group: "appears_on",
        album_type: "compilation",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Various Artists",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of",
          },
        ],
        available_markets: [
          "AD",
          "AG",
          "AL",
          "AR",
          "AU",
          "BA",
          "BB",
          "BD",
          "BE",
          "BG",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CW",
          "CY",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GB",
          "GD",
          "GR",
          "GT",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JP",
          "KH",
          "KI",
          "KN",
          "KR",
          "LA",
          "LC",
          "LI",
          "LK",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "ME",
          "MH",
          "MK",
          "MO",
          "MT",
          "MV",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PT",
          "PW",
          "PY",
          "RO",
          "RS",
          "SB",
          "SE",
          "SG",
          "SI",
          "SM",
          "SR",
          "SV",
          "TH",
          "TL",
          "TN",
          "TO",
          "TT",
          "TV",
          "TW",
          "US",
          "UY",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/24nhPPOmRDre6oBvhKKRQA",
        },
        href: "https://api.spotify.com/v1/albums/24nhPPOmRDre6oBvhKKRQA",
        id: "24nhPPOmRDre6oBvhKKRQA",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b27358aeaf44b2de7620bfe08356",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e0258aeaf44b2de7620bfe08356",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d0000485158aeaf44b2de7620bfe08356",
            width: 64,
          },
        ],
        name: "The Osbourne Family Album (Clean Version)",
        release_date: "1964",
        release_date_precision: "year",
        total_tracks: 27,
        type: "album",
        uri: "spotify:album:24nhPPOmRDre6oBvhKKRQA",
      },
    ],
    limit: 20,
    next: "https://api.spotify.com/v1/artists/5eAWCfyUhZtHHtBdNk56l1/albums?include_groups=album,single,compilation,appears_on&offset=20&limit=20",
    offset: 0,
    previous: null,
    total: 35,
  },
  headers: {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "public, max-age=7200",
    "x-robots-tag": "noindex, nofollow",
    "access-control-allow-origin": "*",
    "access-control-allow-headers":
      "Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token",
    "access-control-allow-methods": "GET, POST, OPTIONS, PUT, DELETE, PATCH",
    "access-control-allow-credentials": "true",
    "access-control-max-age": "604800",
    "content-encoding": "gzip",
    "strict-transport-security": "max-age=31536000",
    "x-content-type-options": "nosniff",
    date: "Sat, 03 Jun 2023 01:05:45 GMT",
    server: "envoy",
    via: "HTTP/2 edgeproxy, 1.1 google",
    "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: "close",
    "transfer-encoding": "chunked",
  },
  statusCode: 200,
}